### ISSUE TITLE
Option for Xanmod Kernel?

### ISSUE THREAD

**Issue by CodeWithShreyans** [arcolinux/arcod-calamares-config#5]
There is a slight performance gain sometimes compared to the zen kernel.

**Comment by samurailostinjapan** [comment]
We provide the Officially supported kernels as listed in the archwiki.

**Comment by CodeWithShreyans** [comment]
The xanmod kernel is unofficial but is listed in the archwiki.

**Comment by arcolinuxz** [comment]
If you can get this kernel in the official repositories of Arch Linux then we would be interested

Ask Arch Linux to include it.
