### ISSUE TITLE
Question: Are the applications chosen in Calamares installed from the AUR?

### ISSUE THREAD

**Issue by CodeWithShreyans** [arcolinux/arcod-calamares-config#6]

**Comment by samurailostinjapan** [comment]
No, if the package is in the AUR, we bring into our repos, no packages are installed directly from the AUR.

**Comment by CodeWithShreyans** [comment]
So everytime an application is updated in the AUR, it is also updated in the repo?

**Comment by CodeWithShreyans** [comment]
So if an application is in the AUR and also in the Arco repos, then will yay install from repo or AUR?

**Comment by samurailostinjapan** [comment]
If a package is updated in the AUR - we will update our packag - this is done a daily basis

**Comment by samurailostinjapan** [comment]
if you have the arcolinux keyring you will get the package from our repo

**Comment by CodeWithShreyans** [comment]
Understood
